aws:
  region: us-east-1
  SNSTopicARN: 'arn:aws:sns:us-east-1:123456789012:YourSNSTopic'
  services:
    - EC2
    - RDS

thresholds:
  ec2_cpu_utilization: 30
  rds_cpu_utilization: 25

protected_resources:

ai:
  claude_api_key: 'YOUR_CLAUDE_API_KEY'
  confidence_threshold: 0.75

notifications:
  slack_webhook_url: 'https://hooks.slack.com/services/XXXXX/XXXXX/XXXXX'
  email:
    from: 'noreply@company.com'
    to:
      - 'devops@company.com'
